name: Commit Message Lint

on:
  workflow_call:
    secrets:
      CI_STANDARDS_TOKEN:
        required: true 

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the consumer repo (the repo where the push/PR happened)
      - name: Checkout consumer repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Checkout the central ci-standards repo to access config & package.json
      - name: Checkout ci-standards
        uses: actions/checkout@v4
        with:
          repository: neoaistriq/ci-standards
          token: ${{ secrets.CI_STANDARDS_TOKEN }}  #PAT token received from consumer repo for read acess to ci-standards on runner
          path: ci-standards
          ref: main
          fetch-depth: 1        
          persist-credentials: false  # do not try to use PAT for write operation
          fetch-tags: false

      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies from ci-standards
      - run: npm ci
        working-directory: ci-standards

      # Run commitlint against the consumer repo commits
      - run: npx commitlint --from=HEAD~1 --to=HEAD --config ci-standards/.github/commitlint.config.js
