name: Commit Message Lint

on:
  workflow_call:
    secrets:
      CI_STANDARDS_TOKEN:
        required: true 

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the consumer repo (the repo where the push/PR happened)
      - name: Checkout consumer repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2   

      - name: Manual clone ci-standards
        run: |
          git clone --depth 1 --single-branch --branch feature/ranjan-2 https://x-access-token:${{ secrets.CI_STANDARDS_TOKEN }}@github.com/neoaistriq/ci-standards.git ci-standards
          
      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies from ci-standards
      - run: npm ci
        working-directory: ci-standards

      # Run commitlint against the consumer repo commits
      - run: npx commitlint --from=HEAD~1 --to=HEAD --config ci-standards/.github/commitlint.config.js
